### ISSUE TITLE
Props not defined correctly

### ISSUE THREAD

**Issue by walsquared** [umaib/arrowPasswordScheme3008#1]
My bad, I didn't catch this when I was telling you which props to use.

React components only take one argument, and that's an object for props, like so:
```javascript
// Brackets around arguments are optional when there's only one parameter
const App = (props) => {...} 
```

As you may know, in JavaScript you can do something called [Destructuring](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment), which allows you to assign names to properties or elements of an object or array respectively. Oftentimes, to help with linting and documentation, you'll use this in a React component to define _what_ properties are in the props object, like so:
```javascript
const App = ({propOne, propTwo, ...theRest}) => {...}
```

However, you can see that in our `App.js` we're missing a pair of `{}`
https://github.com/umaib/arrowPasswordScheme3008/blob/08cb2da716cf74ed22be920aaa3bf10bbb07c617/src/App.js#L4

Just add those brackets and you'll be good to go 👍

**Comment by umaib** [comment]
Thanks for the explanation and examples Wal! :)
