### ISSUE TITLE
Call to 'alert()' causes a delay in logging

### ISSUE THREAD

**Issue by walsquared** [umaib/arrowPasswordScheme3008#3]
See [App.js](https://github.com/umaib/arrowPasswordScheme3008/blob/08cb2da716cf74ed22be920aaa3bf10bbb07c617/src/App.js) lines 15-22.

Calling `alert()` pauses the JavaScript thread, meaning the following `onCorrect()`/`onIncorrect()` on the following line will be called once it's dismissed. Since logging will happen in these functions, they need to occur as soon as the user gets the password correct, otherwise it'll seem that it takes a couple seconds longer for us to register the result.

**Comment by umaib** [comment]
That makes sense, we'll work on that. Thank you!
